version: '2.1'

services:
  postgres_miem:
    image: postgres:14.0
    environment:
      POSTGRES_PASSWORD: postgres
    expose:
      - 5432
    ports:
      - 5430:5432

  minio_miem:
    image: bitnami/minio:latest
    expose:
      - 9000
    ports:
      - "9000:9000"
    environment:
      MINIO_ACCESS_KEY: DLTcaJR6C16c
      MINIO_SECRET_KEY: N2jkevoAzumN
      MINIO_DEFAULT_BUCKETS: 'miemfinancedev'
