version: '2.1'

services:

  miem_finance:
    image: 'miemfinance:latest'
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: miem_finance
    depends_on:
      - postgres_miem
      - minio_miem
    ports:
      - 8443:8443
    environment:
      - DATABASE_URL=jdbc:postgresql://postgres_miem:5432/postgres
      - DATABASE_USER=postgres
      - DATABASE_PASSWORD=postgres
      - MIEMFINANCE_APP_INITIALIZATION=true
      - MIEMFINANCE_SSO_ENABLED=true
      - MIEMFINANCE_STORAGE_ENDPOINT=http://minio_miem:9000

  postgres_miem:
    image: postgres:14.0
    environment:
      POSTGRES_PASSWORD: postgres
    expose:
      - 5432
    ports:
      - 5430:5432

  minio_miem:
    image: bitnami/minio:2021.6.17
    expose:
      - 9000
    ports:
      - "9000:9000"
    environment:
      MINIO_ACCESS_KEY: DLTcaJR6C16c
      MINIO_SECRET_KEY: N2jkevoAzumN
      MINIO_DEFAULT_BUCKETS: 'miemfinancedev'
