spring:
  datasource:
    url: jdbc:postgresql://localhost:5430/postgres
    username: postgres
    password: postgres
  liquibase:
    change-log: classpath:/db/migration/liquibase/master.xml

miemfinance:
  sso-enabled: false
